description = "Spring JDBC"

dependencies {
	compile(project(":spring-beans"))
	compile(project(":spring-core"))
	compile(project(":spring-tx"))
	compileOnly(project(":spring-context"))  // for JndiDataSourceLookup
	compileOnly("javax.transaction:javax.transaction-api:1.2")
	compileOnly("org.hsqldb:hsqldb:${hsqldbVersion}")
	compileOnly("com.h2database:h2:1.4.197")
	compileOnly("org.apache.derby:derby:10.14.2.0")
	compileOnly("org.apache.derby:derbyclient:10.14.2.0")
	compileOnly("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
	compileOnly("org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}")
}
