description = "Spring WebFlux"

dependencyManagement {
	imports {
		mavenBom "io.projectreactor:reactor-bom:${reactorVersion}"
		mavenBom "io.netty:netty-bom:${nettyVersion}"
	}
}

dependencies {
	compile(project(":spring-beans"))
	compile(project(":spring-core"))
	compile(project(":spring-web"))
	compile("io.projectreactor:reactor-core")
	compileOnly(project(":spring-context"))
	compileOnly(project(":spring-context-support"))  // for FreeMarker support
	compileOnly("javax.servlet:javax.servlet-api:3.1.0")
	compileOnly("javax.websocket:javax.websocket-api:1.1")
	compileOnly("org.webjars:webjars-locator-core:0.35")
	compileOnly("org.freemarker:freemarker:${freemarkerVersion}")
	compileOnly("com.fasterxml.jackson.core:jackson-databind:${jackson2Version}")
	compileOnly("com.fasterxml.jackson.dataformat:jackson-dataformat-smile:${jackson2Version}")
	compileOnly("io.reactivex:rxjava:${rxjavaVersion}")
	compileOnly("io.reactivex:rxjava-reactive-streams:${rxjavaAdapterVersion}")
	compileOnly("io.projectreactor.ipc:reactor-netty")
	compileOnly("org.apache.tomcat:tomcat-websocket:${tomcatVersion}") {
		exclude group: "org.apache.tomcat", module: "tomcat-websocket-api"
		exclude group: "org.apache.tomcat", module: "tomcat-servlet-api"
	}
	compileOnly("org.eclipse.jetty.websocket:websocket-server:${jettyVersion}") {
		exclude group: "javax.servlet", module: "javax.servlet"
	}
	compileOnly("io.undertow:undertow-websockets-jsr:${undertowVersion}") {
		exclude group: "org.jboss.spec.javax.websocket", module: "jboss-websocket-api_1.1_spec"
	}
	compileOnly("org.apache.httpcomponents:httpclient:4.5.5") {
		exclude group: "commons-logging", module: "commons-logging"
	}
	compileOnly("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
	compileOnly("org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}")
	testCompile("javax.xml.bind:jaxb-api:2.3.0")
	testCompile("com.fasterxml:aalto-xml:1.0.0")
	testCompile("org.hibernate:hibernate-validator:6.0.10.Final")
	testCompile "io.reactivex.rxjava2:rxjava:${rxjava2Version}"
	testCompile("io.projectreactor:reactor-test")
	testCompile("io.undertow:undertow-core:${undertowVersion}")
	testCompile("org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}")
	testCompile("org.apache.tomcat:tomcat-util:${tomcatVersion}")
	testCompile("org.eclipse.jetty:jetty-server:${jettyVersion}")
	testCompile("org.eclipse.jetty:jetty-servlet:${jettyVersion}")
	testCompile("com.squareup.okhttp3:mockwebserver:3.10.0")
	testCompile("org.jetbrains.kotlin:kotlin-script-runtime:${kotlinVersion}")
	testRuntime("org.jetbrains.kotlin:kotlin-script-util:${kotlinVersion}")
	testRuntime("org.jetbrains.kotlin:kotlin-compiler:${kotlinVersion}")
	testRuntime("org.jruby:jruby:9.1.16.0")
	testRuntime("org.python:jython-standalone:2.7.1")
	testRuntime("org.synchronoss.cloud:nio-multipart-parser:1.1.0")
	testRuntime("org.webjars:underscorejs:1.8.3")
	testRuntime("org.glassfish:javax.el:3.0.1-b08")
	testRuntime("com.sun.xml.bind:jaxb-core:2.3.0")
	testRuntime("com.sun.xml.bind:jaxb-impl:2.3.0")
	testRuntime("com.sun.activation:javax.activation:1.2.0")
}
