description = "Spring JMS"

dependencies {
	compileOnly("javax.jms:javax.jms-api:2.0.1")
	compile(project(":spring-beans"))
	compile(project(":spring-core"))
	compile(project(":spring-messaging"))
	compile(project(":spring-tx"))
	compileOnly(project(":spring-aop"))
	compileOnly(project(":spring-context"))
	compileOnly(project(":spring-oxm"))
	compileOnly("javax.resource:javax.resource-api:1.7")
	compileOnly("javax.transaction:javax.transaction-api:1.2")
	compileOnly("com.fasterxml.jackson.core:jackson-databind:${jackson2Version}")
}
